"""first migration

Revision ID: 3a124f1df37d
Revises: 
Create Date: 2023-11-08 02:49:30.610586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a124f1df37d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('log_category', sa.String(length=99), nullable=False),
    sa.Column('log_category1', sa.String(length=99), nullable=True),
    sa.Column('log_category2', sa.String(length=99), nullable=True),
    sa.Column('log_from_id', sa.String(length=255), nullable=False),
    sa.Column('log_from_root_id', sa.String(length=255), nullable=False),
    sa.Column('log_type', sa.Enum('INFO', 'WARN', 'DANGER', name='logtype'), nullable=False),
    sa.Column('log_msg', sa.String(length=255), nullable=True),
    sa.Column('log_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('log_resolved', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(length=99), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_apps',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('app_name', sa.String(length=99), nullable=False),
    sa.Column('app_username', sa.String(length=99), nullable=False),
    sa.Column('app_enabled', sa.Boolean(), nullable=True),
    sa.Column('app_linked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('source_app_id', sa.String(length=255), nullable=False),
    sa.Column('project_path', sa.String(length=255), nullable=True),
    sa.Column('project_title', sa.String(length=255), nullable=True),
    sa.Column('project_diagnosed', sa.Boolean(), nullable=True),
    sa.Column('project_datasource_fetched', sa.Boolean(), nullable=True),
    sa.Column('project_output_fetched', sa.Boolean(), nullable=True),
    sa.Column('project_synced_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('project_token', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['source_app_id'], ['source_apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pfiles',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('pfile_name', sa.String(length=255), nullable=False),
    sa.Column('pfile_url', sa.String(length=999), nullable=True),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('pfile_type', sa.Enum('datasource', 'output', 'schema'), nullable=False),
    sa.Column('pfile_of_id', sa.String(length=255), nullable=True),
    sa.Column('pfile_col_types', sa.JSON(), nullable=True),
    sa.Column('synced_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('token', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pfiles')
    op.drop_table('projects')
    op.drop_table('source_apps')
    op.drop_table('logs')
    # ### end Alembic commands ###
